#!/usr/bin/env python

import os
import sys
import dicom
from string import maketrans   # Required to call maketrans function.

# read in the datafile
if len(sys.argv) != 2:
    print("usage: dorenamedicom directoryname inputfile")
    exit()
indirname = sys.argv[1]
infilename = sys.argv[2]
plan = dicom.read_file(indirname + "/" + infilename)
# print plan
seriesnostr = plan.SeriesNumber
imagenostr = plan.AcquisitionNumber
protocolname = plan.SeriesDescription
tempstring = protocolname + "_" + str(seriesnostr)
thelist = tempstring.split()
dirname = indirname + "/" + ''.join(thelist)
outfilename = "IM-" + str(seriesnostr).rjust(4, '0') + "-" + str(imagenostr).rjust(4, '0') + ".dcm"
print(dirname, outfilename)
if not os.path.isdir(dirname + "/"):
    os.mkdir(dirname + "/")
namestring = dirname + "/" + outfilename
os.rename(indirname + "/" + infilename, namestring)
