#!/usr/bin/env python

import sys
import dicom


def getsiemensmrheader(theplan):
    datadict = {}
    SiemensCSAHeader2 = theplan[0x0029, 0x1020].value
    startposition = SiemensCSAHeader2.find('### ASCCONV BEGIN ###') + len('### ASCCONV BEGIN ###')
    endposition = SiemensCSAHeader2.find('### ASCCONV END ###')
    InterestingSiemensHeader = SiemensCSAHeader2[startposition:endposition].splitlines()
    for theline in InterestingSiemensHeader[1:]:
        thepair = theline.split()
        datadict[thepair[0]] = thepair[2]

    return datadict

if len(sys.argv) != 2:
    print("usage: getdicominfo inputfile")
    exit()
filename = sys.argv[1]
plan = dicom.read_file(filename)
timestr = float(plan.AcquisitionTime)
thetr = float(plan.RepetitionTime)
timeconv = 3600 * (int(timestr / 10000) % 100) + 60 * (int(timestr / 100) % 100) + timestr % 100 + (timestr - int(timestr))
acqnum = plan.AcquisitionNumber

print(plan[0x0010, 0x0010].value)
