#!/usr/bin/env python

import os
import sys
import dicom


def clean(instring):
    return instring.replace(" ", "_").replace('"', '').replace("'", "").replace(", ", " ")


def readrfpulses(theheader):
    numrfpulses = 0
    thepulses = []
    therearepulses = True
    while therearepulses:
        rootname = 'sTXSPEC.aRFPULSE[' + str(numrfpulses) + '].'
        thepulse = []
        for field in ('tName', 'flAmplitude'):
            try:
                thedata = theheader[rootname + field]
            except KeyError:
                therearepulses = False
            else:
                thepulse.append(clean(thedata))
        thepulses.append(thepulse)
        numrfpulses = numrfpulses + 1
    return thepulses


def getsiemensmrheader(theplan):
    datadict = {}
    allheaderspresent = True
    try:
        SiemensCSAHeader = theplan[0x0029, 0x0010].value
    except KeyError:
        allheaderspresent = False

    try:
        SeriesHeader = theplan[0x0029, 0x1020].value
    except KeyError:
        allheaderspresent = False

    try:
        ImageHeader = theplan[0x0029, 0x1010].value
    except KeyError:
        allheaderspresent = False

    try:
        SiemensCSAHeader2 = theplan[0x0029, 0x1020].value
    except KeyError:
        allheaderspresent = False

    if allheaderspresent:
        startposition = SiemensCSAHeader2.find('### ASCCONV BEGIN ###') + len('### ASCCONV BEGIN ###')
        endposition = SiemensCSAHeader2.find('### ASCCONV END ###')
        InterestingSiemensHeader = SiemensCSAHeader2[startposition:endposition].splitlines()
        for theline in InterestingSiemensHeader[1:]:
            thepair = theline.split()
            datadict[thepair[0]] = thepair[2]

    return datadict

if len(sys.argv) != 2:
    print("usage: getdicominfo inputfile")
    exit()
filename = sys.argv[1]
plan = dicom.read_file(filename)

timestr = float(plan.AcquisitionTime)
thetr = float(plan.RepetitionTime)
thete = float(plan.EchoTime)
timeconv = 3600 * (int(timestr / 10000) % 100) + 60 * (int(timestr / 100) % 100) + timestr % 100 + (timestr - int(timestr))
acqnum = plan.AcquisitionNumber
thesiemensheader = getsiemensmrheader(plan)

if thesiemensheader != {}:
    slicethickness = thesiemensheader['sSliceArray.asSlice[0].dThickness']
    patmode = thesiemensheader['sPat.ucPATMode']
    thepulses = readrfpulses(thesiemensheader)
    imagingfreq = thesiemensheader['sTXSPEC.asNucleusInfo[0].lFrequency']
    refamplitude = thesiemensheader['sTXSPEC.asNucleusInfo[0].flReferenceAmplitude']

sex = plan[0x0010, 0x0040].value
age = plan[0x0010, 0x1010].value
weight = plan[0x0010, 0x1030].value
orientation = plan[0x0051, 0x100e].value
flip = plan[0x0018, 0x1314].value
sar = plan[0x0018, 0x1316].value
protocol = clean(plan[0x0018, 0x1030].value)
sequence = clean(plan[0x0018, 0x0024].value)
reqproc = clean(plan[0x0032, 0x1060].value)
try:
    date = plan[0x0008, 0x0012].value
except KeyError:
    print(filename, ' has no date field')
else:
    thepath = os.path.dirname(filename)
    print(thepath, '\t',\
        date, '\t', timestr, '\t', protocol, '\t', sex, '\t', age, '\t', weight)
