#!/usr/bin/env python

import os
import sys
import dicom


def clean(instring):
    return instring.replace(" ", "_").replace('"', '').replace("'", "").replace(", ", " ")


def readrfpulses(theheader):
    numrfpulses = 0
    thepulses = []
    therearepulses = True
    while therearepulses:
        rootname = 'sTXSPEC.aRFPULSE[' + str(numrfpulses) + '].'
        thepulse = []
        for field in ('tName', 'flAmplitude'):
            try:
                thedata = theheader[rootname + field]
            except KeyError:
                therearepulses = False
            else:
                thepulse.append(clean(thedata))
        thepulses.append(thepulse)
        numrfpulses = numrfpulses + 1
    return thepulses


def getsiemensmrheader(theplan):
    datadict = {}
    allheaderspresent = True
    try:
        SiemensCSAHeader = theplan[0x0029, 0x0010].value
    except KeyError:
        allheaderspresent = False

    try:
        SeriesHeader = theplan[0x0029, 0x1020].value
        # print SeriesHeader
    except KeyError:
        allheaderspresent = False

    try:
        ImageHeader = theplan[0x0029, 0x1010].value
        # print "############################ IMAGE ####################################"
        # print ImageHeader
    except KeyError:
        allheaderspresent = False

    try:
        SiemensCSAHeader2 = theplan[0x0029, 0x1020].value
    except KeyError:
        allheaderspresent = False

    if allheaderspresent:
        startposition = SiemensCSAHeader2.find('### ASCCONV BEGIN ###') + len('### ASCCONV BEGIN ###')
        endposition = SiemensCSAHeader2.find('### ASCCONV END ###')
        InterestingSiemensHeader = SiemensCSAHeader2[startposition:endposition].splitlines()
        for theline in InterestingSiemensHeader[1:]:
            thepair = theline.split()
            # print thepair
            datadict[thepair[0]] = thepair[2]

    return datadict

# read in the datafile
if len(sys.argv) != 2:
    print("usage: getdicominfo inputfile")
    exit()
filename = sys.argv[1]
plan = dicom.read_file(filename)

# print 'Metadata:'
# print plan.file_meta
# print
# print
# print
# print 'Dicom Header:'
# print plan

#

# You don't want to look up here ^
timestr = float(plan.AcquisitionTime)
thetr = float(plan.RepetitionTime)
thete = float(plan.EchoTime)
timeconv = 3600 * (int(timestr / 10000) % 100) + 60 * (int(timestr / 100) % 100) + timestr % 100 + (timestr - int(timestr))
acqnum = plan.AcquisitionNumber
thesiemensheader = getsiemensmrheader(plan)
# print thesiemensheader
if thesiemensheader != {}:
    # this is where you get things from the Siemens header (things in square brackets)
    slicethickness = thesiemensheader['sSliceArray.asSlice[0].dThickness']
    # reflines=thesiemensheader['sPat.lRefLinesPE']
    patmode = thesiemensheader['sPat.ucPATMode']
    thepulses = readrfpulses(thesiemensheader)
    imagingfreq = thesiemensheader['sTXSPEC.asNucleusInfo[0].lFrequency']
    refamplitude = thesiemensheader['sTXSPEC.asNucleusInfo[0].flReferenceAmplitude']
    #diffweight = thesiemensheader['sDiffusion.lDiffWeightings']
    #Bvalue = thesiemensheader['sDiffusion.alBValue[1]']
    #noiselevel = thesiemensheader['sDiffusion.lNoiseLevel']
    #diffdir = thesiemensheader['sDiffusion.lDiffDirections']
    #mode = thesiemensheader['sDiffusion.ulMode']
    #txamp = thesiemensheader['sTXSPEC.aRFPULSE[0].flAmplitude']

# print txspec

# this is how you get things from the dicom header
# slices=plan[0x0018,0x0095].value
flip = plan[0x0018, 0x1314].value
print('flip=', flip)
rows = plan[0x0028, 0x0010].value
print('rows=', rows)
columns = plan[0x0028, 0x0011].value
print('columns=', columns)
vres = plan[0x0028, 0x0030].value
vresx = vres[0]
vresy = vres[1]
print('vresx=', vresx)
print('vresy=', vresy)
print('slicethickness=', slicethickness)
print('TR=', thetr)
print('TE=', thete)
pixelbw = plan[0x0018, 0x0095].value
print('pixelbw=', pixelbw)
pedir = plan[0x0018, 0x1312].value
print('pedir=', pedir)
orientation = plan[0x0051, 0x100e].value
print('orientation=', orientation)
posdirs = plan[0x0051, 0x1013].value
print('posdirs=', posdirs)
tablepos = plan[0x0019, 0x1014].value
print('tablepos=', tablepos)
imsinmosaic = plan[0x0019, 0x100a].value
print('imsinmosaic=', imsinmosaic)
coil = plan[0x0051, 0x100f].value
print('coil=', coil)
# print thepath,'\t',\
#    date,'\t',timestr,'\t',protocol,'\t',sequence,'\t',thetr,'\t',thete,'\t',patmode,'\t',acqnum,'\t',\
#    slicethickness,'\t',patmode,'\t',\
#    sar,'\t',flip,'\t',imagingfreq,'\t',refamplitude,'\t',reqproc,'\t',thepulses
