#!/bin/csh -f

setenv dicombasedir	'/Users/frederic/Documents/MR_data/stability_tracking_raw'
setenv fslbasedir	'/Users/frederic/Documents/MR_data/stability_tracking'
setenv subjname		$1
setenv funcremap	'x -y z'

pushd $dicombasedir/$1
setenv boldname `'ls' -1d ep2d_bold_normalize_* | egrep -v adaptive | tail -n 1`
setenv pacename `'ls' -1d ep2d_pace_normalize_* | egrep -v adaptive | tail -n 1`
setenv singleslicename `'ls' -1d epi_stability_single*sPlot* | tail -n 1`
popd

if( $pacename != '' ) then
    echo 'PACE name: ' $pacename
    newprocfuncs $dicombasedir $fslbasedir $subjname $pacename epi_pace "$funcremap"
    studyinfo $dicombasedir'/'$subjname'/'$pacename'/'IM*0001.dcm > $fslbasedir'/'$subjname'/epi_pace/studyinfo'
    stabilitycalc $fslbasedir/$subjname/epi_pace epi_pace.nii.gz 10
    chmod -R a+r $fslbasedir/$subjname/epi_pace

    pushd $dicombasedir/$1
    setenv com_x	`cat $fslbasedir/$subjname/epi_pace/procresults/analysissummary.txt | grep center_of_mass_x | awk '{print $2}'`
    setenv com_y	`cat $fslbasedir/$subjname/epi_pace/procresults/analysissummary.txt | grep center_of_mass_y | awk '{print $2}'`
    setenv com_z	`cat $fslbasedir/$subjname/epi_pace/procresults/analysissummary.txt | grep center_of_mass_z | awk '{print $2}'`
    echo $com_x' '$com_y' '$com_z
    'ls' -1d uncombined* | sed 's/uncombined//g' | sed 's/_/ /g' | awk '{print "processonestability mysubjname uncombined"$1"_"$2" element "$1" mycom"}' | sed 's/mysubjname/'$subjname'/g' | sed 's/mycom/'$com_x' '$com_y' '$com_z'/g' > $dicombasedir/$subjname/elementlist
    source $dicombasedir/$subjname/elementlist
    popd
    stabilitysummary $fslbasedir /Volumes/stability epi_pace &
endif

if( $singleslicename != '' ) then
    echo 'SS name: ' $singleslicename
    newprocfuncs $dicombasedir $fslbasedir $subjname $singleslicename epi_singleslice "$funcremap"
    studyinfo $dicombasedir'/'$subjname'/'$singleslicename'/'IM*0001.dcm > $fslbasedir'/'$subjname'/epi_singleslice/studyinfo'
    stabilitycalc $fslbasedir/$subjname/epi_singleslice epi_singleslice.nii.gz 10
    chmod -R a+r $fslbasedir/$subjname/epi_singleslice
    stabilitysummary $fslbasedir /Volumes/stability epi_singleslice &
endif

if( $boldname != '' ) then
    echo 'BOLD name: ' $boldname
    newprocfuncs $dicombasedir $fslbasedir $subjname $boldname epi_bold "$funcremap"
    studyinfo $dicombasedir'/'$subjname'/'$boldname'/'IM*0001.dcm > $fslbasedir'/'$subjname'/epi_bold/studyinfo'
    stabilitycalc $fslbasedir/$subjname/epi_bold epi_bold.nii.gz 10
    chmod -R a+r $fslbasedir/$subjname/epi_bold 
    stabilitysummary $fslbasedir /Volumes/stability epi_bold &
endif

touch $fslbasedir/$subjname
