#!/bin/csh -f

setenv rawdicomdir	`stabilityparms RAWDICOMDIR`
setenv sorteddicomdir	`stabilityparms SORTEDDICOMDIR`
setenv processedscandir	`stabilityparms PROCESSEDSCANDIR`
setenv outputdir	`stabilityparms OUTPUTDIR`

setenv session		$1
setenv elementinname	$2
setenv elementoutbase	$3
setenv elementoutsuffix	$4
setenv com_x		$5
setenv com_y		$6
setenv com_z		$7
setenv funcremap	'x -y z'
if( -e $sorteddicomdir'/'$session'/'$elementinname ) then
    dicom2nifti.py $sorteddicomdir/$session/$elementinname $processedscandir/$session $elementoutbase'_'$elementoutsuffix 
    studyinfo.py $sorteddicomdir'/'$session'/'$elementinname'/'IM*0001.dcm > $processedscandir'/'$session'/'$elementoutbase'_'$elementoutsuffix'/studyinfo'
    stabilitycalc $processedscandir/$session/$elementoutbase'_'$elementoutsuffix $elementoutbase'_'$elementoutsuffix'.nii.gz' 0 $com_x $com_y $com_z
endif

