#!/bin/csh -f

setenv rawdicomdir	`stabilityparms RAWDICOMDIR`
setenv sorteddicomdir	`stabilityparms SORTEDDICOMDIR`
setenv processedscandir	`stabilityparms PROCESSEDSCANDIR`
setenv outputdir	`stabilityparms OUTPUTDIR`

stabilitysummary --nonbirn $processedscandir $outputdir/3T/nonbirn epi_pace
stabilitysummary --nonbirn $processedscandir $outputdir/3T/nonbirn epi_bold
stabilitysummary --nonbirn $processedscandir $outputdir/3T/nonbirn epi_singleslice
