#!/bin/csh -f

setenv rawdicomdir	`stabilityparms RAWDICOMDIR`
setenv sorteddicomdir	`stabilityparms SORTEDDICOMDIR`
setenv processedscandir	`stabilityparms PROCESSEDSCANDIR`
setenv outputdir	`stabilityparms OUTPUTDIR`

stabilitysummary $processedscandir $outputdir/3T/birn epi_pace
stabilitysummary $processedscandir $outputdir/3T/birn epi_bold
stabilitysummary $processedscandir $outputdir/3T/birn epi_singleslice

setenv outputdir	/Volumes/Stability/stability

stabilitysummary $processedscandir $outputdir/3T/birn epi_pace
stabilitysummary $processedscandir $outputdir/3T/birn epi_bold
stabilitysummary $processedscandir $outputdir/3T/birn epi_singleslice
