#!/bin/csh -f

setenv rawdicomdir	`stabilityparms RAWDICOMDIR`
setenv sorteddicomdir	`stabilityparms SORTEDDICOMDIR`
setenv processedscandir	`stabilityparms PROCESSEDSCANDIR`
setenv outputdir	`stabilityparms OUTPUTDIR`
setenv subjname		$1
setenv funcremap	'x -y z'

pushd $sorteddicomdir/$1
setenv boldname `'ls' -1d ep2d_bold_normalize_* | egrep -v adaptive | tail -n 1`
setenv pacename `'ls' -1d ep2d_pace_normalize_* | egrep -v adaptive | tail -n 1`
setenv multiflip10name `'ls' -1d ep2d_multiflip_10_* | tail -n 1`
setenv multiflip77name `'ls' -1d ep2d_multiflip_77_* | tail -n 1`
setenv singleslicename `'ls' -1d epi_stability_single*sPlot* | tail -n 1`
popd

setenv doregen	True
if( $0 == 'reprocessstability_noregen' ) then
    echo 'not regenerating'
    setenv doregen	False
    endif

if( $boldname != '' ) then
    echo 'BOLD name: ' $boldname
    studyinfo $sorteddicomdir'/'$subjname'/'$boldname'/'IM*0001.dcm > $processedscandir'/'$subjname'/epi_bold/studyinfo'
    stabilitycalc $processedscandir/$subjname/epi_bold epi_bold.nii.gz 10
    chmod -R a+r $processedscandir/$subjname/epi_bold
    if ( doregen == True ) then
        stabilitysummary $processedscandir $outputdir'/3T/birn' epi_bold
        stabilitysummary $processedscandir $outputdir'/3T/nonbirn' epi_bold
        endif
    endif

if( $pacename != '' ) then
    echo 'PACE name: ' $pacename
    studyinfo $sorteddicomdir'/'$subjname'/'$pacename'/'IM*0001.dcm > $processedscandir'/'$subjname'/epi_pace/studyinfo'
    stabilitycalc $processedscandir/$subjname/epi_pace epi_pace.nii.gz 10
    chmod -R a+r $processedscandir/$subjname/epi_pace
    pushd $sorteddicomdir/$1
    setenv com_x	`cat $processedscandir/$subjname/epi_pace/procresults/analysissummary.txt | grep center_of_mass_x | awk '{print $2}'`
    setenv com_y	`cat $processedscandir/$subjname/epi_pace/procresults/analysissummary.txt | grep center_of_mass_y | awk '{print $2}'`
    setenv com_z	`cat $processedscandir/$subjname/epi_pace/procresults/analysissummary.txt | grep center_of_mass_z | awk '{print $2}'`
    echo $com_x' '$com_y' '$com_z
    'ls' -1d uncombined* | sed 's/uncombined//g' | sed 's/_/ /g' | awk '{print "reprocessonestability mysubjname uncombined"$1"_"$2" element "$1" mycom"}' | sed 's/mysubjname/'$subjname'/g' | sed 's/mycom/'$com_x' '$com_y' '$com_z'/g' > $sorteddicomdir/$subjname/elementlist
    if ( doregen == True ) then
        stabilitysummary $processedscandir $outputdir'/3T/birn' epi_pace
        stabilitysummary $processedscandir $outputdir'/3T/nonbirn' epi_pace
	endif
    source $sorteddicomdir/$subjname/elementlist
    popd
    endif

if( $multiflip10name != '' ) then
    echo 'Multiflip_10 name: ' $multiflip10name
    studyinfo $sorteddicomdir'/'$subjname'/'$multiflip10name'/'IM*0001.dcm > $processedscandir'/'$subjname'/epi_multiflip10/studyinfo'
    stabilitycalc $processedscandir/$subjname/epi_multiflip10 epi_multiflip10.nii.gz 10
    chmod -R a+r $processedscandir/$subjname/epi_multiflip10 
    if ( doregen == True ) then
        stabilitysummary $processedscandir $outputdir'/3T/birn' epi_multiflip10 &
        stabilitysummary --nonbirn $processedscandir $outputdir'/3T/nonbirn' epi_multiflip10 &
	endif
    endif

if( $multiflip77name != '' ) then
    echo 'Multiflip_77 name: ' $multiflip77name
    studyinfo $sorteddicomdir'/'$subjname'/'$multiflip77name'/'IM*0001.dcm > $processedscandir'/'$subjname'/epi_multiflip77/studyinfo'
    stabilitycalc $processedscandir/$subjname/epi_multiflip77 epi_multiflip77.nii.gz 10
    chmod -R a+r $processedscandir/$subjname/epi_multiflip77 
    if ( doregen == True ) then
        stabilitysummary $processedscandir $outputdir'/3T/birn' epi_multiflip77 &
        stabilitysummary --nonbirn $processedscandir $outputdir'/3T/nonbirn' epi_multiflip77 &
	endif
    endif

if( $singleslicename != '' ) then
    echo 'SS name: ' $singleslicename
    studyinfo $sorteddicomdir'/'$subjname'/'$singleslicename'/'IM*0001.dcm > $processedscandir'/'$subjname'/epi_singleslice/studyinfo'
    stabilitycalc $processedscandir/$subjname/epi_singleslice epi_singleslice.nii.gz 10
    chmod -R a+r $processedscandir/$subjname/epi_singleslice
    if ( doregen == True ) then
        stabilitysummary $processedscandir $outputdir'/3T/birn' epi_singleslice
        stabilitysummary $processedscandir $outputdir'/3T/nonbirn' epi_singleslice
	endif
    endif

touch $processedscandir/$subjname
