#!/usr/bin/env python

from stabilityfuncs import stabilityparms

import argparse
import logging
logging.basicConfig(format='%(levelname)s:%(message)s')

parser = argparse.ArgumentParser(description='Retrieve a value from the configuration file.')
parser.add_argument('option', help='The option to retrieve.')
parser.add_argument('--section', '-s', default='paths')
args = parser.parse_args()

print(stabilityparms(option=args.option, section=args.section))
