#!/usr/bin/env python

import sys
import os
import dicom


def getsiemensmrheader(theplan):
    SiemensCSAHeader2 = theplan[0x0029, 0x1020].value
    startposition = SiemensCSAHeader2.find('### ASCCONV BEGIN ###') + len('### ASCCONV BEGIN ###')
    partialheader = SiemensCSAHeader2[startposition:]
    endposition = partialheader.find('### ASCCONV END ###')
    textversion = partialheader[:endposition]
    InterestingSiemensHeader = textversion.splitlines()
    datadict = {}
    for theline in InterestingSiemensHeader[1:]:
        thepair = theline.split()
        datadict[thepair[0]] = thepair[2]
    return datadict, textversion

# send a command to the shell


def doashellcmd(cmd):
    a = os.popen(cmd)
    while True:
        line = a.readline()
        if not line:
            break
        retval = line[:-1]
        return retval

# read the command line parameters
fulldump = False
if (len(sys.argv) < 2) or (len(sys.argv) > 3):
    print("usage: studyinfo dicomfilename [-f]")
    exit()
dicomfilename = sys.argv[1]
if(len(sys.argv) == 3):
    if(sys.argv[2] == "-f"):
        fulldump = True
    else:
        print("usage: studyinfo dicomfilename [-f]")
        exit()
plan = dicom.read_file(dicomfilename)
thesiemensheader, textversion = getsiemensmrheader(plan)
coilname = thesiemensheader['asCoilSelectMeas[0].asList[0].sCoilElementID.tCoilID'].strip('"')
timestr = plan.StudyTime
datestr = plan.StudyDate
acqnum = plan.AcquisitionNumber
if fulldump:
    print(plan)
    print(textversion)
else:
    print("Coil: " + coilname)
    print("StudyDate: " + datestr)
    print("StudyTime: " + timestr)
    try:
        elementnumber = plan[0x0051, 0x100f].value
    except KeyError:
        elementnumber = 0
        print("ElementName: UNKNOWN")
    else:
        print("ElementName: " + elementnumber)
