#!/usr/bin/env python
#
#       $Author: frederic $
#       $Date: 2011/02/15 00:14:02 $
#       $Id: showtclims,v 1.1 2011/02/15 00:14:02 frederic Exp $
#
import sys
import matplotlib
matplotlib.use('WxAgg')
from scipy import arange
import stabilityfuncs as sf
import pylab as P

# set default variable values
dolegend = True

# handle required args first
textfilename = []
xvecs = []
yvecs = []
legendvecs = []
specvals = []

xvecs.append(arange(0.0, 100.0, 1.0))
yvecs.append(xvecs[0] * 2.0)
legendvecs.append("times 2")
specvals.append('ro')
xvecs.append(arange(0.0, 100.0, 1.0))
yvecs.append(xvecs[1] * 3.0)
legendvecs.append("times 3")
specvals.append('g^')

dolegend = 1
hoot = sf.showvals(xvecs, yvecs, legendvecs, specvals, "test", dolegend)
P.show()
