#!/bin/bash

# test to make sure nothing has changed.
# numbers come out different on unix and mac so we
# have separate baseline dirs
DATA=/Users/dmd/mcldata
if [ -z "$DATA" ]; then
    # out of an abundance of caution because of next line
    exit 1
fi
for COIL in TxRx 32Ch; do
    rm -rf $DATA/test$COIL/procresults
done
./stabilitycalc $DATA/test32Ch epi_pace.nii.gz 0
./stabilitycalc $DATA/testTxRx epi_short.nii.gz 0
failed=0
for COIL in TxRx 32Ch; do
    echo ==================
    echo diff $COIL
    echo ==================
    diff <(sort $DATA/test$COIL/procresults/dataquality.txt) <(sort $DATA/test$COIL.orig/procresults/dataquality.txt)
    if [ $? -ne 0 ]; then failed=1; fi
    diff <(sort $DATA/test$COIL/procresults/analysissummary.txt) <(sort $DATA/test$COIL.orig/procresults/analysissummary.txt)
    if [ $? -ne 0 ]; then failed=1; fi
    diff <(grep -v "generated on" $DATA/test$COIL/procresults/output.html) <(grep -v "generated on" $DATA/test$COIL.orig/procresults/output.html)
    if [ $? -ne 0 ]; then failed=1; fi
    echo 
    echo Image diffs:
    for IMAGE in $DATA/test$COIL/procresults/*png; do
        gm compare -metric mse $IMAGE $DATA/test$COIL.orig/procresults/$(basename $IMAGE) | grep Total | grep -v "Total: 0.0000000000        0.0"
    done
done
if [ $failed -ne 0 ]; then
    echo TESTS FAILED
fi
