#!/bin/bash

# test to make sure nothing has changed.
# numbers come out different on unix and mac so we
# have separate baseline dirs

./stabilitycalc data/testdata epi_short.nii.gz 0
echo ==================
echo diff
echo ==================
diff <(sort data/testdata/procresults/dataquality.txt) <(sort data/testdata.orig.$(uname)/procresults/dataquality.txt)
diff <(sort data/testdata/procresults/analysissummary.txt) <(sort data/testdata.orig.$(uname)/procresults/analysissummary.txt)
