#!/bin/csh -f
#
#       $Author: frederic $
#       $Date: 2011/09/01 19:27:51 $
#       $Id: updatestability,v 1.3 2011/09/01 19:27:51 frederic Exp $
#
setenv	rawdicomdir	`stabilityparms RAWDICOMDIR`
setenv	sorteddicomdir	`stabilityparms SORTEDDICOMDIR`

renamestabilitydata $rawdicomdir $sorteddicomdir
